[package]
name = "spirolab-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.31.1"
egui = "0.31.1"
env_logger = "0.11.7"
log = "0.4.27"
num = "0.4.3"
rand = "0.9.0"

[profile.dev]
opt-level = 3